services:
  api:
    build:
      dockerfile: ./deploy/Dockerfile
      context: .
    volumes:
      - "./settings.yaml:/code/settings.yaml:ro" # Read-only settings file
    depends_on:
      db:
        condition: service_started
    restart: always
    ports:
      - "8000:8000"
    env_file: .env
